#include "Param.h"

#include <boost/property_tree/xml_parser.hpp>
#include <iostream>
#include <string>
#include <math.h>

namespace pt = boost::property_tree;
namespace CancerVCT{
using std::string;
using std::vector;

#define PARAM_DESCRIPTION_FIELD_COUNT 3
const char* _description[][PARAM_DESCRIPTION_FIELD_COUNT] =
{
    //simulation settings
    {"Param.QSP.simulation.start","",""},//0
    {"Param.QSP.simulation.step","",""},//1
    {"Param.QSP.simulation.n_step","",""},//2
    {"Param.QSP.simulation.tol_rel","",""},//3
    {"Param.QSP.simulation.tol_abs","",""},//4
    //compartments
    {"Param.QSP.init_value.Compartment.V_C","",""},//5|5
    {"Param.QSP.init_value.Compartment.V_P","",""},//6|6
    {"Param.QSP.init_value.Compartment.V_T","",""},//7|7
    {"Param.QSP.init_value.Compartment.V_LN","",""},//8|8
    {"Param.QSP.init_value.Compartment.V_e","",""},//9|9
    {"Param.QSP.init_value.Compartment.A_e","",""},//10|10
    {"Param.QSP.init_value.Compartment.A_s","",""},//11|11
    {"Param.QSP.init_value.Compartment.syn_T_C1","",""},//12|12
    {"Param.QSP.init_value.Compartment.syn_T_APC","",""},//13|13
    //species
    {"Param.QSP.init_value.Species.V_C_T0","",""},//14|14
    {"Param.QSP.init_value.Species.V_C_T1","",""},//15|15
    {"Param.QSP.init_value.Species.V_C_nivo","",""},//16|16
    {"Param.QSP.init_value.Species.V_C_durv","",""},//17|17
    {"Param.QSP.init_value.Species.V_C_ipi","",""},//18|18
    {"Param.QSP.init_value.Species.V_C_ENT","",""},//19|19
    {"Param.QSP.init_value.Species.V_C_ENT_Buccal","",""},//20|20
    {"Param.QSP.init_value.Species.V_C_ENT_GI","",""},//21|21
    {"Param.QSP.init_value.Species.V_C_Dose2","",""},//22|22
    {"Param.QSP.init_value.Species.V_P_T0","",""},//23|23
    {"Param.QSP.init_value.Species.V_P_T1","",""},//24|24
    {"Param.QSP.init_value.Species.V_P_nivo","",""},//25|25
    {"Param.QSP.init_value.Species.V_P_durv","",""},//26|26
    {"Param.QSP.init_value.Species.V_P_ipi","",""},//27|27
    {"Param.QSP.init_value.Species.V_P_Treg_CTLA4","",""},//28|28
    {"Param.QSP.init_value.Species.V_P_Treg_CTLA4_ipi","",""},//29|29
    {"Param.QSP.init_value.Species.V_P_Treg_CTLA4_ipi_CTLA4","",""},//30|30
    {"Param.QSP.init_value.Species.V_P_ENT","",""},//31|31
    {"Param.QSP.init_value.Species.V_T_C_x","",""},//32|32
    {"Param.QSP.init_value.Species.V_T_T_exh","",""},//33|33
    {"Param.QSP.init_value.Species.V_T_C1","",""},//34|34
    {"Param.QSP.init_value.Species.V_T_T0","",""},//35|35
    {"Param.QSP.init_value.Species.V_T_T1","",""},//36|36
    {"Param.QSP.init_value.Species.V_T_APC","",""},//37|37
    {"Param.QSP.init_value.Species.V_T_mAPC","",""},//38|38
    {"Param.QSP.init_value.Species.V_T_c","",""},//39|39
    {"Param.QSP.init_value.Species.V_T_nivo","",""},//40|40
    {"Param.QSP.init_value.Species.V_T_durv","",""},//41|41
    {"Param.QSP.init_value.Species.V_T_ipi","",""},//42|42
    {"Param.QSP.init_value.Species.V_T_Treg_CTLA4","",""},//43|43
    {"Param.QSP.init_value.Species.V_T_Treg_CTLA4_ipi","",""},//44|44
    {"Param.QSP.init_value.Species.V_T_Treg_CTLA4_ipi_CTLA4","",""},//45|45
    {"Param.QSP.init_value.Species.V_T_MDSC","",""},//46|46
    {"Param.QSP.init_value.Species.V_T_CCL2","",""},//47|47
    {"Param.QSP.init_value.Species.V_T_NO","",""},//48|48
    {"Param.QSP.init_value.Species.V_T_ArgI","",""},//49|49
    {"Param.QSP.init_value.Species.V_T_ENT","",""},//50|50
    {"Param.QSP.init_value.Species.V_LN_nT0","",""},//51|51
    {"Param.QSP.init_value.Species.V_LN_aT0","",""},//52|52
    {"Param.QSP.init_value.Species.V_LN_T0","",""},//53|53
    {"Param.QSP.init_value.Species.V_LN_IL2","",""},//54|54
    {"Param.QSP.init_value.Species.V_LN_nT1","",""},//55|55
    {"Param.QSP.init_value.Species.V_LN_aT1","",""},//56|56
    {"Param.QSP.init_value.Species.V_LN_T1","",""},//57|57
    {"Param.QSP.init_value.Species.V_LN_APC","",""},//58|58
    {"Param.QSP.init_value.Species.V_LN_mAPC","",""},//59|59
    {"Param.QSP.init_value.Species.V_LN_P0","",""},//60|60
    {"Param.QSP.init_value.Species.V_LN_P1","",""},//61|61
    {"Param.QSP.init_value.Species.V_LN_nivo","",""},//62|62
    {"Param.QSP.init_value.Species.V_LN_durv","",""},//63|63
    {"Param.QSP.init_value.Species.V_LN_ipi","",""},//64|64
    {"Param.QSP.init_value.Species.V_LN_ENT","",""},//65|65
    {"Param.QSP.init_value.Species.V_e_P0","",""},//66|66
    {"Param.QSP.init_value.Species.V_e_p0","",""},//67|67
    {"Param.QSP.init_value.Species.V_e_P1","",""},//68|68
    {"Param.QSP.init_value.Species.V_e_p1","",""},//69|69
    {"Param.QSP.init_value.Species.A_e_M1","",""},//70|70
    {"Param.QSP.init_value.Species.A_e_M1p0","",""},//71|71
    {"Param.QSP.init_value.Species.A_e_M1p1","",""},//72|72
    {"Param.QSP.init_value.Species.A_s_M1","",""},//73|73
    {"Param.QSP.init_value.Species.A_s_M1p0","",""},//74|74
    {"Param.QSP.init_value.Species.A_s_M1p1","",""},//75|75
    {"Param.QSP.init_value.Species.syn_T_C1_PD1_PDL1","",""},//76|76
    {"Param.QSP.init_value.Species.syn_T_C1_PD1_PDL2","",""},//77|77
    {"Param.QSP.init_value.Species.syn_T_C1_PD1","",""},//78|78
    {"Param.QSP.init_value.Species.syn_T_C1_PDL1","",""},//79|79
    {"Param.QSP.init_value.Species.syn_T_C1_PDL2","",""},//80|80
    {"Param.QSP.init_value.Species.syn_T_C1_PD1_nivo","",""},//81|81
    {"Param.QSP.init_value.Species.syn_T_C1_PD1_nivo_PD1","",""},//82|82
    {"Param.QSP.init_value.Species.syn_T_C1_PDL1_durv","",""},//83|83
    {"Param.QSP.init_value.Species.syn_T_C1_PDL1_durv_PDL1","",""},//84|84
    {"Param.QSP.init_value.Species.syn_T_C1_TPDL1","",""},//85|85
    {"Param.QSP.init_value.Species.syn_T_C1_TPDL1_durv","",""},//86|86
    {"Param.QSP.init_value.Species.syn_T_C1_TPDL1_durv_TPDL1","",""},//87|87
    {"Param.QSP.init_value.Species.syn_T_C1_CD28_CD80","",""},//88|88
    {"Param.QSP.init_value.Species.syn_T_C1_CD28_CD80_CD28","",""},//89|89
    {"Param.QSP.init_value.Species.syn_T_C1_CD28_CD86","",""},//90|90
    {"Param.QSP.init_value.Species.syn_T_C1_CD80_CTLA4","",""},//91|91
    {"Param.QSP.init_value.Species.syn_T_C1_CD80_CTLA4_CD80","",""},//92|92
    {"Param.QSP.init_value.Species.syn_T_C1_CTLA4_CD80_CTLA4","",""},//93|93
    {"Param.QSP.init_value.Species.syn_T_C1_CD80_CTLA4_CD80_CTLA4","",""},//94|94
    {"Param.QSP.init_value.Species.syn_T_C1_CD86_CTLA4","",""},//95|95
    {"Param.QSP.init_value.Species.syn_T_C1_CD86_CTLA4_CD86","",""},//96|96
    {"Param.QSP.init_value.Species.syn_T_C1_TPDL1_CD80","",""},//97|97
    {"Param.QSP.init_value.Species.syn_T_C1_TPDL1_CD80_TPDL1","",""},//98|98
    {"Param.QSP.init_value.Species.syn_T_C1_CD28","",""},//99|99
    {"Param.QSP.init_value.Species.syn_T_C1_CTLA4","",""},//100|100
    {"Param.QSP.init_value.Species.syn_T_C1_CD80","",""},//101|101
    {"Param.QSP.init_value.Species.syn_T_C1_CD86","",""},//102|102
    {"Param.QSP.init_value.Species.syn_T_C1_CTLA4_ipi","",""},//103|103
    {"Param.QSP.init_value.Species.syn_T_C1_CTLA4_ipi_CTLA4","",""},//104|104
    {"Param.QSP.init_value.Species.syn_T_APC_PD1_PDL1","",""},//105|105
    {"Param.QSP.init_value.Species.syn_T_APC_PD1_PDL2","",""},//106|106
    {"Param.QSP.init_value.Species.syn_T_APC_PD1","",""},//107|107
    {"Param.QSP.init_value.Species.syn_T_APC_PDL1","",""},//108|108
    {"Param.QSP.init_value.Species.syn_T_APC_PDL2","",""},//109|109
    {"Param.QSP.init_value.Species.syn_T_APC_PD1_nivo","",""},//110|110
    {"Param.QSP.init_value.Species.syn_T_APC_PD1_nivo_PD1","",""},//111|111
    {"Param.QSP.init_value.Species.syn_T_APC_PDL1_durv","",""},//112|112
    {"Param.QSP.init_value.Species.syn_T_APC_PDL1_durv_PDL1","",""},//113|113
    {"Param.QSP.init_value.Species.syn_T_APC_TPDL1","",""},//114|114
    {"Param.QSP.init_value.Species.syn_T_APC_TPDL1_durv","",""},//115|115
    {"Param.QSP.init_value.Species.syn_T_APC_TPDL1_durv_TPDL1","",""},//116|116
    {"Param.QSP.init_value.Species.syn_T_APC_CD28_CD80","",""},//117|117
    {"Param.QSP.init_value.Species.syn_T_APC_CD28_CD80_CD28","",""},//118|118
    {"Param.QSP.init_value.Species.syn_T_APC_CD28_CD86","",""},//119|119
    {"Param.QSP.init_value.Species.syn_T_APC_CD80_CTLA4","",""},//120|120
    {"Param.QSP.init_value.Species.syn_T_APC_CD80_CTLA4_CD80","",""},//121|121
    {"Param.QSP.init_value.Species.syn_T_APC_CTLA4_CD80_CTLA4","",""},//122|122
    {"Param.QSP.init_value.Species.syn_T_APC_CD80_CTLA4_CD80_CTLA4","",""},//123|123
    {"Param.QSP.init_value.Species.syn_T_APC_CD86_CTLA4","",""},//124|124
    {"Param.QSP.init_value.Species.syn_T_APC_CD86_CTLA4_CD86","",""},//125|125
    {"Param.QSP.init_value.Species.syn_T_APC_TPDL1_CD80","",""},//126|126
    {"Param.QSP.init_value.Species.syn_T_APC_TPDL1_CD80_TPDL1","",""},//127|127
    {"Param.QSP.init_value.Species.syn_T_APC_CD28","",""},//128|128
    {"Param.QSP.init_value.Species.syn_T_APC_CTLA4","",""},//129|129
    {"Param.QSP.init_value.Species.syn_T_APC_CD80","",""},//130|130
    {"Param.QSP.init_value.Species.syn_T_APC_CD86","",""},//131|131
    {"Param.QSP.init_value.Species.syn_T_APC_CTLA4_ipi","",""},//132|132
    {"Param.QSP.init_value.Species.syn_T_APC_CTLA4_ipi_CTLA4","",""},//133|133
    //parameters
    {"Param.QSP.init_value.Parameter.k_cell_clear","",""},//134|134
    {"Param.QSP.init_value.Parameter.cell","",""},//135|135
    {"Param.QSP.init_value.Parameter.day","",""},//136|136
    {"Param.QSP.init_value.Parameter.vol_cell","",""},//137|137
    {"Param.QSP.init_value.Parameter.vol_Tcell","",""},//138|138
    {"Param.QSP.init_value.Parameter.V_Tmin","",""},//139|139
    {"Param.QSP.init_value.Parameter.C_total","",""},//140|140
    {"Param.QSP.init_value.Parameter.T_total","",""},//141|141
    {"Param.QSP.init_value.Parameter.T_total_LN","",""},//142|142
    {"Param.QSP.init_value.Parameter.R_Tcell","",""},//143|143
    {"Param.QSP.init_value.Parameter.Tregs_","",""},//144|144
    {"Param.QSP.init_value.Parameter.H_APC","",""},//145|145
    {"Param.QSP.init_value.Parameter.H_mAPC","",""},//146|146
    {"Param.QSP.init_value.Parameter.H_PD1_C1","",""},//147|147
    {"Param.QSP.init_value.Parameter.H_PD1_APC","",""},//148|148
    {"Param.QSP.init_value.Parameter.H_CD28_C1","",""},//149|149
    {"Param.QSP.init_value.Parameter.H_CD28_APC","",""},//150|150
    {"Param.QSP.init_value.Parameter.H_MDSC_C1","",""},//151|151
    {"Param.QSP.init_value.Parameter.H_ENT_C1","",""},//152|152
    {"Param.QSP.init_value.Parameter.k_C1_growth","",""},//153|153
    {"Param.QSP.init_value.Parameter.C_max","",""},//154|154
    {"Param.QSP.init_value.Parameter.k_C1_death","",""},//155|155
    {"Param.QSP.init_value.Parameter.k_C1_therapy","",""},//156|156
    {"Param.QSP.init_value.Parameter.initial_tumour_diameter","",""},//157|157
    {"Param.QSP.init_value.Parameter.n_T0_clones","",""},//158|158
    {"Param.QSP.init_value.Parameter.Q_T0_in","",""},//159|159
    {"Param.QSP.init_value.Parameter.Q_T0_out","",""},//160|160
    {"Param.QSP.init_value.Parameter.k_T0_act","",""},//161|161
    {"Param.QSP.init_value.Parameter.k_T0_pro","",""},//162|162
    {"Param.QSP.init_value.Parameter.k_T0_death","",""},//163|163
    {"Param.QSP.init_value.Parameter.q_T0_P_in","",""},//164|164
    {"Param.QSP.init_value.Parameter.q_T0_P_out","",""},//165|165
    {"Param.QSP.init_value.Parameter.q_T0_T_in","",""},//166|166
    {"Param.QSP.init_value.Parameter.q_T0_LN_out","",""},//167|167
    {"Param.QSP.init_value.Parameter.k_IL2_deg","",""},//168|168
    {"Param.QSP.init_value.Parameter.k_IL2_cons","",""},//169|169
    {"Param.QSP.init_value.Parameter.k_IL2_sec","",""},//170|170
    {"Param.QSP.init_value.Parameter.IL2_50","",""},//171|171
    {"Param.QSP.init_value.Parameter.IL2_50_Treg","",""},//172|172
    {"Param.QSP.init_value.Parameter.N0","",""},//173|173
    {"Param.QSP.init_value.Parameter.N_costim","",""},//174|174
    {"Param.QSP.init_value.Parameter.N_IL2","",""},//175|175
    {"Param.QSP.init_value.Parameter.k_Treg","",""},//176|176
    {"Param.QSP.init_value.Parameter.H_P0","",""},//177|177
    {"Param.QSP.init_value.Parameter.N_aT","",""},//178|178
    {"Param.QSP.init_value.Parameter.n_T1_clones","",""},//179|179
    {"Param.QSP.init_value.Parameter.Q_T1_in","",""},//180|180
    {"Param.QSP.init_value.Parameter.Q_T1_out","",""},//181|181
    {"Param.QSP.init_value.Parameter.k_T1_act","",""},//182|182
    {"Param.QSP.init_value.Parameter.k_T1_pro","",""},//183|183
    {"Param.QSP.init_value.Parameter.k_T1_death","",""},//184|184
    {"Param.QSP.init_value.Parameter.q_T1_P_in","",""},//185|185
    {"Param.QSP.init_value.Parameter.q_T1_P_out","",""},//186|186
    {"Param.QSP.init_value.Parameter.q_T1_T_in","",""},//187|187
    {"Param.QSP.init_value.Parameter.q_T1_LN_out","",""},//188|188
    {"Param.QSP.init_value.Parameter.k_T1","",""},//189|189
    {"Param.QSP.init_value.Parameter.k_C_T1","",""},//190|190
    {"Param.QSP.init_value.Parameter.H_P1","",""},//191|191
    {"Param.QSP.init_value.Parameter.k_APC_mat","",""},//192|192
    {"Param.QSP.init_value.Parameter.k_APC_mig","",""},//193|193
    {"Param.QSP.init_value.Parameter.k_APC_death","",""},//194|194
    {"Param.QSP.init_value.Parameter.k_mAPC_death","",""},//195|195
    {"Param.QSP.init_value.Parameter.APC0_T","",""},//196|196
    {"Param.QSP.init_value.Parameter.APC0_LN","",""},//197|197
    {"Param.QSP.init_value.Parameter.k_c","",""},//198|198
    {"Param.QSP.init_value.Parameter.c0","",""},//199|199
    {"Param.QSP.init_value.Parameter.c50","",""},//200|200
    {"Param.QSP.init_value.Parameter.DAMPs","",""},//201|201
    {"Param.QSP.init_value.Parameter.n_sites_APC","",""},//202|202
    {"Param.QSP.init_value.Parameter.kin","",""},//203|203
    {"Param.QSP.init_value.Parameter.kout","",""},//204|204
    {"Param.QSP.init_value.Parameter.k_P0_up","",""},//205|205
    {"Param.QSP.init_value.Parameter.k_xP0_deg","",""},//206|206
    {"Param.QSP.init_value.Parameter.k_P0_deg","",""},//207|207
    {"Param.QSP.init_value.Parameter.k_p0_deg","",""},//208|208
    {"Param.QSP.init_value.Parameter.k_P0_on","",""},//209|209
    {"Param.QSP.init_value.Parameter.k_P0_d1","",""},//210|210
    {"Param.QSP.init_value.Parameter.p0_50","",""},//211|211
    {"Param.QSP.init_value.Parameter.P0_C1","",""},//212|212
    {"Param.QSP.init_value.Parameter.A_syn","",""},//213|213
    {"Param.QSP.init_value.Parameter.A_Tcell","",""},//214|214
    {"Param.QSP.init_value.Parameter.A_cell","",""},//215|215
    {"Param.QSP.init_value.Parameter.A_APC","",""},//216|216
    {"Param.QSP.init_value.Parameter.k_M1p0_TCR_on","",""},//217|217
    {"Param.QSP.init_value.Parameter.k_M1p0_TCR_off","",""},//218|218
    {"Param.QSP.init_value.Parameter.TCR_p0_tot","",""},//219|219
    {"Param.QSP.init_value.Parameter.pTCR_p0_MHC_tot","",""},//220|220
    {"Param.QSP.init_value.Parameter.k_P1_up","",""},//221|221
    {"Param.QSP.init_value.Parameter.k_xP1_deg","",""},//222|222
    {"Param.QSP.init_value.Parameter.k_P1_deg","",""},//223|223
    {"Param.QSP.init_value.Parameter.k_p1_deg","",""},//224|224
    {"Param.QSP.init_value.Parameter.k_P1_on","",""},//225|225
    {"Param.QSP.init_value.Parameter.k_P1_d1","",""},//226|226
    {"Param.QSP.init_value.Parameter.p1_50","",""},//227|227
    {"Param.QSP.init_value.Parameter.P1_C1","",""},//228|228
    {"Param.QSP.init_value.Parameter.k_M1p1_TCR_on","",""},//229|229
    {"Param.QSP.init_value.Parameter.k_M1p1_TCR_off","",""},//230|230
    {"Param.QSP.init_value.Parameter.k_M1p1_TCR_p","",""},//231|231
    {"Param.QSP.init_value.Parameter.phi_M1p1_TCR","",""},//232|232
    {"Param.QSP.init_value.Parameter.N_M1p1_TCR","",""},//233|233
    {"Param.QSP.init_value.Parameter.TCR_p1_tot","",""},//234|234
    {"Param.QSP.init_value.Parameter.pTCR_p1_MHC_tot","",""},//235|235
    {"Param.QSP.init_value.Parameter.kon_PD1_PDL1","",""},//236|236
    {"Param.QSP.init_value.Parameter.q_P_nivo","",""},//237|237
    {"Param.QSP.init_value.Parameter.q_T_nivo","",""},//238|238
    {"Param.QSP.init_value.Parameter.q_LN_nivo","",""},//239|239
    {"Param.QSP.init_value.Parameter.q_LD_nivo","",""},//240|240
    {"Param.QSP.init_value.Parameter.k_cl_nivo","",""},//241|241
    {"Param.QSP.init_value.Parameter.gamma_C_nivo","",""},//242|242
    {"Param.QSP.init_value.Parameter.gamma_P_nivo","",""},//243|243
    {"Param.QSP.init_value.Parameter.gamma_T_nivo","",""},//244|244
    {"Param.QSP.init_value.Parameter.gamma_LN_nivo","",""},//245|245
    {"Param.QSP.init_value.Parameter.q_P_durv","",""},//246|246
    {"Param.QSP.init_value.Parameter.q_T_durv","",""},//247|247
    {"Param.QSP.init_value.Parameter.q_LN_durv","",""},//248|248
    {"Param.QSP.init_value.Parameter.q_LD_durv","",""},//249|249
    {"Param.QSP.init_value.Parameter.k_cl_durv","",""},//250|250
    {"Param.QSP.init_value.Parameter.gamma_C_durv","",""},//251|251
    {"Param.QSP.init_value.Parameter.gamma_P_durv","",""},//252|252
    {"Param.QSP.init_value.Parameter.gamma_T_durv","",""},//253|253
    {"Param.QSP.init_value.Parameter.gamma_LN_durv","",""},//254|254
    {"Param.QSP.init_value.Parameter.q_P_ipi","",""},//255|255
    {"Param.QSP.init_value.Parameter.q_T_ipi","",""},//256|256
    {"Param.QSP.init_value.Parameter.q_LN_ipi","",""},//257|257
    {"Param.QSP.init_value.Parameter.q_LD_ipi","",""},//258|258
    {"Param.QSP.init_value.Parameter.k_cl_ipi","",""},//259|259
    {"Param.QSP.init_value.Parameter.gamma_C_ipi","",""},//260|260
    {"Param.QSP.init_value.Parameter.gamma_P_ipi","",""},//261|261
    {"Param.QSP.init_value.Parameter.gamma_T_ipi","",""},//262|262
    {"Param.QSP.init_value.Parameter.gamma_LN_ipi","",""},//263|263
    {"Param.QSP.init_value.Parameter.kon_PD1_PDL2","",""},//264|264
    {"Param.QSP.init_value.Parameter.kon_PD1_nivo","",""},//265|265
    {"Param.QSP.init_value.Parameter.kon_PDL1_durv","",""},//266|266
    {"Param.QSP.init_value.Parameter.kon_CD28_CD80","",""},//267|267
    {"Param.QSP.init_value.Parameter.kon_CD28_CD86","",""},//268|268
    {"Param.QSP.init_value.Parameter.kon_CTLA4_CD80","",""},//269|269
    {"Param.QSP.init_value.Parameter.kon_CTLA4_CD86","",""},//270|270
    {"Param.QSP.init_value.Parameter.kon_CD80_PDL1","",""},//271|271
    {"Param.QSP.init_value.Parameter.kon_CTLA4_ipi","",""},//272|272
    {"Param.QSP.init_value.Parameter.koff_PD1_PDL1","",""},//273|273
    {"Param.QSP.init_value.Parameter.koff_PD1_PDL2","",""},//274|274
    {"Param.QSP.init_value.Parameter.koff_PD1_nivo","",""},//275|275
    {"Param.QSP.init_value.Parameter.koff_PDL1_durv","",""},//276|276
    {"Param.QSP.init_value.Parameter.koff_CD28_CD80","",""},//277|277
    {"Param.QSP.init_value.Parameter.koff_CD28_CD86","",""},//278|278
    {"Param.QSP.init_value.Parameter.koff_CTLA4_CD80","",""},//279|279
    {"Param.QSP.init_value.Parameter.koff_CTLA4_CD86","",""},//280|280
    {"Param.QSP.init_value.Parameter.koff_CD80_PDL1","",""},//281|281
    {"Param.QSP.init_value.Parameter.koff_CTLA4_ipi","",""},//282|282
    {"Param.QSP.init_value.Parameter.Chi_PD1_nivo","",""},//283|283
    {"Param.QSP.init_value.Parameter.Chi_PDL1_durv","",""},//284|284
    {"Param.QSP.init_value.Parameter.Chi_CTLA4_ipi","",""},//285|285
    {"Param.QSP.init_value.Parameter.PD1_50","",""},//286|286
    {"Param.QSP.init_value.Parameter.n_PD1","",""},//287|287
    {"Param.QSP.init_value.Parameter.CD28_CD8X_50","",""},//288|288
    {"Param.QSP.init_value.Parameter.n_CD28_CD8X","",""},//289|289
    {"Param.QSP.init_value.Parameter.T_PD1_total","",""},//290|290
    {"Param.QSP.init_value.Parameter.T_CD28_total","",""},//291|291
    {"Param.QSP.init_value.Parameter.T_CTLA4_syn","",""},//292|292
    {"Param.QSP.init_value.Parameter.T_PDL1_total","",""},//293|293
    {"Param.QSP.init_value.Parameter.C1_PDL1_total","",""},//294|294
    {"Param.QSP.init_value.Parameter.C1_PDL2_total","",""},//295|295
    {"Param.QSP.init_value.Parameter.C1_CD80_total","",""},//296|296
    {"Param.QSP.init_value.Parameter.C1_CD86_total","",""},//297|297
    {"Param.QSP.init_value.Parameter.APC_PDL1_total","",""},//298|298
    {"Param.QSP.init_value.Parameter.APC_PDL2_total","",""},//299|299
    {"Param.QSP.init_value.Parameter.APC_CD80_total","",""},//300|300
    {"Param.QSP.init_value.Parameter.APC_CD86_total","",""},//301|301
    {"Param.QSP.init_value.Parameter.Treg_CTLA4_tot","",""},//302|302
    {"Param.QSP.init_value.Parameter.Treg_CTLA4_50","",""},//303|303
    {"Param.QSP.init_value.Parameter.n_Treg_CTLA4","",""},//304|304
    {"Param.QSP.init_value.Parameter.k_CTLA4_ADCC","",""},//305|305
    {"Param.QSP.init_value.Parameter.H_Treg_T","",""},//306|306
    {"Param.QSP.init_value.Parameter.H_Treg_P","",""},//307|307
    {"Param.QSP.init_value.Parameter.k_rec_MDSC","",""},//308|308
    {"Param.QSP.init_value.Parameter.kd_MDSC","",""},//309|309
    {"Param.QSP.init_value.Parameter.IC50_ENT_C","",""},//310|310
    {"Param.QSP.init_value.Parameter.k_deg_CCL2","",""},//311|311
    {"Param.QSP.init_value.Parameter.k_deg_NO","",""},//312|312
    {"Param.QSP.init_value.Parameter.k_deg_ArgI","",""},//313|313
    {"Param.QSP.init_value.Parameter.k_sec_CCL2","",""},//314|314
    {"Param.QSP.init_value.Parameter.k_sec_NO","",""},//315|315
    {"Param.QSP.init_value.Parameter.k_sec_ArgI","",""},//316|316
    {"Param.QSP.init_value.Parameter.IC50_ENT_NO","",""},//317|317
    {"Param.QSP.init_value.Parameter.ki_Treg","",""},//318|318
    {"Param.QSP.init_value.Parameter.IC50_ArgI_CTL","",""},//319|319
    {"Param.QSP.init_value.Parameter.IC50_NO_CTL","",""},//320|320
    {"Param.QSP.init_value.Parameter.EC50_CCL2_rec","",""},//321|321
    {"Param.QSP.init_value.Parameter.EC50_ArgI_Treg","",""},//322|322
    {"Param.QSP.init_value.Parameter.MDSC_max","",""},//323|323
    {"Param.QSP.init_value.Parameter.Treg_max","",""},//324|324
    {"Param.QSP.init_value.Parameter.IC50_ENT_CCL2","",""},//325|325
    {"Param.QSP.init_value.Parameter.k_brec_MDSC","",""},//326|326
    {"Param.QSP.init_value.Parameter.IC50_ENT_ArgI","",""},//327|327
    {"Param.QSP.init_value.Parameter.k_a1_ENT","",""},//328|328
    {"Param.QSP.init_value.Parameter.k_a2_ENT","",""},//329|329
    {"Param.QSP.init_value.Parameter.k_cln_ENT","",""},//330|330
    {"Param.QSP.init_value.Parameter.Kc_ENT","",""},//331|331
    {"Param.QSP.init_value.Parameter.lagP","",""},//332|332
    {"Param.QSP.init_value.Parameter.durP","",""},//333|333
    {"Param.QSP.init_value.Parameter.k_dose2","",""},//334|334
    {"Param.QSP.init_value.Parameter.q_P_ENT","",""},//335|335
    {"Param.QSP.init_value.Parameter.q_T_ENT","",""},//336|336
    {"Param.QSP.init_value.Parameter.q_LN_ENT","",""},//337|337
    {"Param.QSP.init_value.Parameter.q_LD_ENT","",""},//338|338
    {"Param.QSP.init_value.Parameter.k_cl_ENT","",""},//339|339
    {"Param.QSP.init_value.Parameter.gamma_C_ENT","",""},//340|340
    {"Param.QSP.init_value.Parameter.gamma_P_ENT","",""},//341|341
    {"Param.QSP.init_value.Parameter.gamma_T_ENT","",""},//342|342
    {"Param.QSP.init_value.Parameter.gamma_LN_ENT","",""},//343|343
};

Param::Param()
    :ParamBase()
{
    setupParam();
}

void Param::setupParam(){
    for (size_t i = 0; i < 344; i++)
    {
        _paramDesc.push_back(vector<string>(_description[i], 
            _description[i]+ PARAM_DESCRIPTION_FIELD_COUNT));
    }
    _paramFloat = vector<double>(344, 0);
}

};
